### ISSUE TITLE
Fix doctests

### ISSUE THREAD

**Issue by saraedum** [conda-forge/sage-feedstock#132]
It would be great to make `sage -tp src` pass. (And `sage -tp --long src` as well.)

A [GitLab CI pipeline](https://gitlab.com/saraedum/conda-sagelib-tests/pipelines) runs these doctests, the results of the latest run are:
```
227 failing individual doctests
```

No modules are failing entirely at the moment.

For reference, [here](https://people.debian.org/~thansen/sage-test-status.html) are the corresponding numbers in Debian (for `--long` doctests.)

**TODO**:
- [x] Package jmol - https://github.com/conda-forge/staged-recipes/pull/5996
- [x] Package twisted - https://github.com/conda-forge/staged-recipes/pull/6003
- [x] Add sphinx as a dependency to sage
- [x] Add pillow as a dependency to sage
- [x] Fix brial packaging - https://github.com/conda-forge/brial-feedstock/pull/9
- [x] Install gcc in gitlab CI
- [x] Patch glpk - https://github.com/conda-forge/glpk-feedstock/pull/29
- [x] Make `sage -tp --all` work (instead of specifying the same directories explicitly.)
- [x] the first pexpect call involving R hangs; this is causing the timeouts, please review https://trac.sagemath.org/ticket/25806 to fix this.
- [x] dowgrade ecl, see https://github.com/conda-forge/sage-feedstock/pull/24
- [x] apply https://trac.sagemath.org/ticket/26117 once it has been merged
- [x] apply https://trac.sagemath.org/ticket/25344
- [ ] apply https://trac.sagemath.org/ticket/26326 once it's ready
- [x] apply https://trac.sagemath.org/ticket/25260
- [x] apply https://trac.sagemath.org/ticket/26434 once it's ready
- [x] apply https://trac.sagemath.org/ticket/26451 ~~once it's ready~~
- [x] apply patches from recipe to source tree for testing
- [ ] apply https://trac.sagemath.org/ticket/26454
- [ ] apply https://trac.sagemath.org/ticket/26116 once it's ready
- [ ] apply https://trac.sagemath.org/ticket/26457 once it's ready

**Comment by saraedum** [comment]
There are still some doctests failing, see #129 for the latest but this issues is very outdated by now.
